# Generated by Django 4.2.3 on 2023-10-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_warning_profile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
