# Generated by Django 4.2.3 on 2023-10-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_warning_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='flag',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
