# Generated by Django 4.2.3 on 2023-10-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_warning_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='reset_flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
