# Generated by Django 4.2.3 on 2023-10-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_warning_reset_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
